name: nanoid
version: 0.2.0
author: Rongjian Zhang <pd4d10@gmail.com>
description: A tiny, secure, URL-friendly, unique string ID generator. Dart implementation of ai/nanoid
homepage: https://github.com/pd4d10/nanoid-dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.4
